File management Service
Mohab96/twitter-clone pull request #3
Opened 2024-10-24 11:04 UTC by MostafaFouad0

**CU-8696636j1**
### Overview
This PR introduces a microservice that allows users to upload files. The service stores these files on disk and responds with a unique file ID for retrieval.

### Features Implemented 
- File Upload Endpoint: Accepts an image file via a POST request, stores it on the server and store it's path in a database.
- File Retrieval Endpoint: Gives a way to retrieve an image given its ID.
### Future Work
Messaging Queue Integration: messaging queue for handling file uploads asynchronously, improving scalability, reliability and lower the response time.

2024-10-24 11:04 UTC, Mohab96 commented
Task linked: [CU-8696636j1 Files Management Component](https://app.clickup.com/t/8696636j1)

2024-10-24 18:16 UTC, Mohab96 requested changes
Well done Mostafa, please update the PR according to the comments regarding the PORT env variable and the validation of `fileId`. Any other comments can be treated as future work.

2024-10-24 18:16 UTC, Mohab96 commented on src/services/File Management/controllers/filesControllers.js
> +      return res.status(400).json({
For the sake of consistency, try wrapping any response with wrapper like [this one](https://github.com/Mohab96/online-chess-game/blob/master/src/utils/apiResponse.js) so that when somebody builds a client it can check the status of the response before going into the actual data of the response.

Take [this](https://www.npmjs.com/package/jsend) as a reference.

2024-10-24 18:16 UTC, Mohab96 commented on src/services/File Management/controllers/filesControllers.js
> +    return res.status(500).json({
Try using status codes like [this one](https://github.com/Mohab96/online-chess-game/blob/master/src/utils/statusCodes.js) as it's better than writing the status codes explicitly into the code like this.

2024-10-24 18:16 UTC, Mohab96 commented on src/services/File Management/controllers/filesControllers.js
> +    const file = await prisma.file.findFirst({
Please validate if `fileId` is null or not before querying the DB.

2024-10-24 18:16 UTC, Mohab96 commented on src/services/File Management/server.js
> +  console.log("[!] server is running on port:", process.env.PORT);
replace `process.env.PORT` with `process.env.PORT || 3000` in case the `PORT` wasn't supplied in the `.env` file.

2024-10-27 16:09 UTC, MostafaFouad0 commented
@Mohab96 changes made please take a look

2024-10-28 15:01 UTC, Mohab96 commented
Great work! Please move the `src/services/File Management/utils/` to `src/shared/utils/` and you're good to go.

2024-10-29 20:08 UTC, merged